### ISSUE TITLE
naughty.connect_signal nil value

### ISSUE THREAD

**Issue by NeoScaler** [elenapan/dotfiles#44]
I run into problems when trying to boot up the newest ephemeral setup. Using Ubuntu 19.04 and Awesome 4.3.

```
~/awesome   master  DISPLAY=:1 awesome
error while running function!
stack traceback:
	/home/julian/.config/awesome/notifications.lua:89: in main chunk
	[C]: in function 'require'
	/home/julian/.config/awesome/rc.lua:185: in main chunk
error: /home/julian/.config/awesome/notifications.lua:89: attempt to call a nil value (field 'connect_signal')
2019-08-01 16:36:53 W: awesome: a_glib_poll:438: Last main loop iteration took 0.279459 seconds! Increasing limit for this warning to that value.
```

Any ideas?

**Comment by elenapan** [comment]
Yep, you need to build AwesomeWM from source. Version 4.3 does not include the new notification API, which I am using in this configuration.

**Comment by NeoScaler** [comment]
Thanks, I installed the current version from source, but running still into problems:

> ~/Downloads  DISPLAY=:1 awesome                                   ✔  ⚙  675  17:28:54
> 
> (nm-applet:19413): nm-applet-WARNING **: 17:28:54.972: Error connecting to D-Bus: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 4 matched rules; type="method_call", sender=":1.4580" (uid=1000 pid=19413 comm="nm-applet " label="unconfined") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination=":1.15" (uid=0 pid=1212 comm="/usr/sbin/ModemManager --filter-policy=strict " label="unconfined")
> 2019-08-01 17:28:54 E: awesome: Error during a protected call: /home/julian/.config/awesome/evil/mpd.lua:13: bad argument #1 to 'gsub' (string expected, got nil)
> stack traceback:
> 	[C]: in function 'string.gsub'
> 	/home/julian/.config/awesome/evil/mpd.lua:13: in function </home/julian/.config/awesome/evil/mpd.lua:10>
> 	(...tail calls...)
> 	/usr/local/share/awesome/lib/awful/spawn.lua:484: in function </usr/local/share/awesome/lib/awful/spawn.lua:478>
> 	[C]: in function 'xpcall'
> 	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
> 	(...tail calls...)
> 	/usr/local/share/awesome/lib/awful/spawn.lua:583: in upvalue 'done'
> 	/usr/local/share/awesome/lib/awful/spawn.lua:598: in function </usr/local/share/awesome/lib/awful/spawn.lua:590>
> bash: line 1: inotifywait: command not found
>

**Comment by elenapan** [comment]
It looks like `mpd` is not running, so `mpc` cannot get any info from it.
If you do not use `mpd`you can disable the `mpd` daemon by commenting out `require("evil.mpd")` in `evil/init.lua`.

Also the last error shows you do not have `inotify-tools` installed.

Check out the dependency list in the README to make sure all the required software is installed.

**Comment by NeoScaler** [comment]
You are right, deactivated mpd and installed inotify-tools. Unfortunately this does not fix my main problem: No key bindings are active after booting into awesome, can not even open a terminal. Think I have messes up the configuration somewhere, restarting from scratch.

Thanks for your help!

**Comment by elenapan** [comment]
Right below the dependency list, there are instructions on how to configure default applications (such as terminal). Let me know if you need more help.

**Comment by NeoScaler** [comment]
> Right below the dependency list, there are instructions on how to configure default applications (such as terminal). Let me know if you need more help.

Thanks a lot, I fixed most of the issues. Really great work, the setup looks stunning :)

**Comment by Eragoneq** [comment]
I'm still having an issue even after I built it from the source, could you provide any tips on what cloud I have done wrong? 

`sudo apt build-dep awesome
git clone https://github.com/awesomewm/awesome
cd awesome
make package
sudo apt install *.deb`

I just used this and got no errors during the installation and the package works.

**Comment by elenapan** [comment]
Hi, do you have the same error about `naughty.connect_signal`?
If you have a different error, please post it here, or in a new issue.
([Here](https://github.com/elenapan/dotfiles/issues/42#issuecomment-517195467) is the method I suggest for getting the errors. An alternative is to check your `~/.xsession-errors`, but it could include output from various other programs as well)

Also, just to make sure the version you built from source is successfully installed, check the output of `awesome -v`. It should be something like `awesome v4.3-xxx-yyyyyyyyy` and not just `awesome v4.3`.

**Comment by Eragoneq** [comment]
Yes, I had the same error, but compiling it once more from the master worked, but still some problems remain.

`No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.


(nm-applet:8678): Gtk-WARNING **: 14:36:39.571: Can't set a parent on widget which has a parent
2019-09-01 14:36:39 W: awesome: a_glib_poll:468: Last main loop iteration took 0.288041 seconds! Increasing limit for this warning to that value.
2019-09-01 14:36:39 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/eragoneq/.config/awesome/notifications.lua:274: in function </home/eragoneq/.config/awesome/notifications.lua:257>
	[C]: in field 'emit_signal'
	/home/eragoneq/.config/awesome/evil/battery.lua:25: in upvalue 'callback'
	/usr/local/share/awesome/lib/awful/widget/watch.lua:78: in function </usr/local/share/awesome/lib/awful/widget/watch.lua:77>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:484: in function </usr/local/share/awesome/lib/awful/spawn.lua:478>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:583: in upvalue 'done'
	/usr/local/share/awesome/lib/awful/spawn.lua:598: in function </usr/local/share/awesome/lib/awful/spawn.lua:590>
error: /home/eragoneq/.config/awesome/notifications.lua:274: attempt to compare number with nil
2019-09-01 14:36:39 E: awesome: Error during a protected call: /home/eragoneq/.config/awesome/evil/ram.lua:18: attempt to perform arithmetic on a nil value
stack traceback:
	/home/eragoneq/.config/awesome/evil/ram.lua:18: in upvalue 'callback'
	/usr/local/share/awesome/lib/awful/widget/watch.lua:78: in function </usr/local/share/awesome/lib/awful/widget/watch.lua:77>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:484: in function </usr/local/share/awesome/lib/awful/spawn.lua:478>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:583: in upvalue 'done'
	/usr/local/share/awesome/lib/awful/spawn.lua:598: in function </usr/local/share/awesome/lib/awful/spawn.lua:590>
2019-09-01 14:36:39 E: awesome: Error during a protected call: /home/eragoneq/.config/awesome/evil/mpd.lua:13: bad argument #1 to 'gsub' (string expected, got nil)
stack traceback:
	[C]: in function 'string.gsub'
	/home/eragoneq/.config/awesome/evil/mpd.lua:13: in function </home/eragoneq/.config/awesome/evil/mpd.lua:10>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:484: in function </usr/local/share/awesome/lib/awful/spawn.lua:478>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:583: in upvalue 'done'
	/usr/local/share/awesome/lib/awful/spawn.lua:598: in function </usr/local/share/awesome/lib/awful/spawn.lua:590>
Couldn't watch /sys/class/backlight/?**/brightness: No such file or directory
`

That's how it looks right now for me: 
https://imgur.com/a/vyS2oDo
The notifications are not showing up and the icons are not working properly.

**Comment by elenapan** [comment]
1. You are missing fonts, please download and install the [icon fonts I am using](https://github.com/elenapan/dotfiles#icon-fonts) so that the icons work.

2. It seems that you do not have a backlight device for adjusting brightness. You probably can do that directly through buttons on your monitor. You should comment out `require("evil.brightness")` in `~/.config/awesome/evil/init.lua` to remove that last error.

3. It looks like the command that tries to get your ram usage does not work properly.
What is the output of this command? It is supposed to show how much memory is currently available on your system.
`free -m | grep 'Mem:' | awk '{printf "%d available out of %d\n", $7, $2}'`

4. You probably have installed `mpd` and `mpc` like the dependencies say, but you also need to run `mpd` on startup so that the music widget can print the song info. It is complaining because it cannot get any info.

**Comment by Eragoneq** [comment]
Okay I understand now, but I'm probably not gonna use it for now, because I'd like to learn to do something similar myself. I'm definitely gonna use your repo for inspiration, because your work is really amazing.

And it seems like the 3. command didn't work because of my language on Ubuntu.
Here's a small solution i found that should work with any language:
`free -m | sed -n '2p' | awk '{printf "%d available out of %d\n", $7, $2}'`

**Comment by elenapan** [comment]
Alright then. Thank you for providing that. I did not know system language affected the output of `free`.

You may replace the `grep 'Mem:'` part of the command in `~/.config/awesome/evil/ram.lua` with `sed -n '2p'` and will most probably work. Let me know if you need any more help/info.
