### ISSUE TITLE
[Arch Linux] Volume buttons not working in sidebar

### ISSUE THREAD

**Issue by epsilon-0** [elenapan/dotfiles#7]
The I am clicking on the sidebar on the volume bar and the mute is not toggling.
There are similar errors with `spawn_with_shell` for other commands as well.

**Comment by elenapan** [comment]
I am using [this](https://github.com/elenapan/dotfiles/blob/master/bin/volume-control.sh) script to control the volume. All you have to do is put it somewhere in your $PATH or call it using the full path.

**Comment by epsilon-0** [comment]
Oh most definitely.
I have the script in my path in `~/.local/bin` and am able to use it via command line.
I actually also made a small change to it, as it didn't work out of the box (don't have the computer right now, will tell later).
Only when it is being invoked via `spawn_with_shell`, that it doesn't work.

**Comment by elenapan** [comment]
Does it actually increase/decrease/(un)mute your volume when you use it via command line? I'm not sure what could be wrong. Maybe you have some headphones connected and it is controlling the wrong output device?

**Comment by epsilon-0** [comment]
Oh yea, it works via command line, showing the icon and all.

**Comment by elenapan** [comment]
Since you said muting is not working, I noticed I am toggling the mute on sink `0` instead of `@DEFAULT_SINK@`. I have pushed an update that fixes this. Could you test if that is the problem?

Also I am curious what is that small change you had to make in order for it to work for you.

**Comment by epsilon-0** [comment]
It is still not working. 
Also the change I made was to make the `-R` option into a `-a`, for the notification image.
The `-R` option is no longer supported.

Also the wallpaper is not being set correctly. This actually seems to be a problem with awesome as I tried to use the `gears` library and it didn't work.
Are these dependencies downloaded on the fly? If so this might be a change in the api.

**Comment by elenapan** [comment]
About the `-R` option:
I am using [notify-send.sh](https://github.com/vlevit/notify-send.sh) which supports replacing notifications (I have replaced the original notify-send with it). I need this because when I press my `volume up` button multiple times, I want it to just update the existing notification instead of spawning multiple ones. That is what the `-R` option does.

About the wallpaper:
I use feh to set the wallpaper. Feh creates `~/.fehbg` which contains the last command you used to set the wallpaper. The function `set_wallpaper(s)` in `rc.lua` simply runs `~/.fehbg` on startup. If you would like to use this method, make sure `~/.fehbg` is executable.

    local function set_wallpaper(s)
        -- Wallpaper
        if beautiful.wallpaper then
            local wallpaper = beautiful.wallpaper
            -- If wallpaper is a function, call it with the screen
            if type(wallpaper) == "function" then
                wallpaper = wallpaper(s)
            end
    
            -- Method 1: Built in function
            --gears.wallpaper.maximized(wallpaper, s, true)
    
            -- Method 2: Set theme's wallpaper with feh
            --awful.spawn.with_shell("feh --bg-fill " .. wallpaper)
    
            -- Method 3: Set last wallpaper with feh
            awful.spawn.with_shell(os.getenv("HOME") .. "/.fehbg")
        end
    end

Also take a look at the above snippet, I have commented out the native AwesomeWM method of setting the wallpaper (Method 1). If you want to use it, you need to set a path for your wallpaper image in your `theme.lua` like so `theme.wallpaper = "/path/to/my/wallpaper.png"`.

Now, back to the volume widget.
Do any errors come up when you click it?
Does scrolling to increase/decrease volume work?
Have you tried spawning it by specifying the full path?

**Comment by epsilon-0** [comment]
I actually went back and checked how the `awsetbg` command works. 
It might be better for me to just use `feh` some other lightweight library to do that.

**Comment by epsilon-0** [comment]
Oh lols. I just saw your comment about the wallpaper.
I will indeed do that.

I will also do the `notify-send` change. Thanks for telling me.
It might be worthwhile to add this note in the `README.md`.

The button press on the sidebar is still not working though. WTH.
The right click is working by opening PulseAudio, but not the left click. JFC.

**Comment by elenapan** [comment]
What about scrolling on it to increase/decrease the volume?

**Comment by elenapan** [comment]
Alright, so that means the issue here is the script works but is not being called correctly. Can you try using the full path in `awful.spawn.with_shell`?

**Comment by epsilon-0** [comment]
YOU ARE A GENIUS!!

**Comment by epsilon-0** [comment]
Everything is working now!

**Comment by elenapan** [comment]
Good to know. Did the full path do the trick?

**Comment by epsilon-0** [comment]
It did. Which begs the question why is this happening?
Me thinks that the `$PATH` is not being correctly read when the `$SHELL` is spawned in awful.
Maybe because I am setting the `$PATH` in `.bashrc`?
Should I set it in `.profile`?
I'll check and report

**Comment by elenapan** [comment]
Not sure either. I am am using zsh and I am setting my own custom path in `.zshrc` as well.
Could it be that you renamed the script to something else or you made a typo when you moved it into `~/.local/bin`?

**Comment by epsilon-0** [comment]
Don't think that is the problem.
I am using `bash` so there are subtle differences in setting up the `$PATH`.
I think for now I am going to keep this workaround.

Thanks a lot!
